const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Thư viện TN CMS API',
      version: '1.0.0',
      description: 'RESTful API cho Thư viện TN. Dùng Bearer JWT cho các endpoint /api/admin/* (đăng nhập để lấy token).',
    },
    servers: [{ url: 'http://localhost:5000', description: 'Local dev' }],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
      schemas: {
        Pagination: {
          type: 'object',
          properties: {
            page: { type: 'integer', example: 1 },
            limit: { type: 'integer', example: 20 },
            total: { type: 'integer', example: 100 },
            totalPages: { type: 'integer', example: 5 },
          },
        },
        BaseResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            message: { type: 'string', example: 'Thao tác thành công' },
            data: { type: 'object' },
          },
        },
        ErrorResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string', example: 'Đã có lỗi xảy ra' },
            error_code: { type: 'string', example: 'INTERNAL_SERVER_ERROR' },
          },
        },
        AuditLog: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            user_id: { type: 'integer', nullable: true },
            user_name: { type: 'string' },
            action: { type: 'string', example: 'UPDATE' },
            module: { type: 'string', example: 'COURSE' },
            entity_id: { type: 'string' },
            description: { type: 'string' },
            old_data: { type: 'object', nullable: true },
            new_data: { type: 'object', nullable: true },
            ip_address: { type: 'string' },
            user_agent: { type: 'string' },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        MembershipRequest: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            member_id: { type: 'integer' },
            member_name: { type: 'string' },
            plan_id: { type: 'integer' },
            plan_name: { type: 'string' },
            amount: { type: 'number' },
            request_note: { type: 'string' },
            status: { type: 'string', enum: ['pending', 'approved', 'rejected'] },
            admin_note: { type: 'string', nullable: true },
            processed_by: { type: 'integer', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            processed_at: { type: 'string', format: 'date-time', nullable: true },
          },
        },
        Course: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            title: { type: 'string' },
            slug: { type: 'string' },
            description: { type: 'string' },
            category_id: { type: 'integer' },
            instructor_id: { type: 'integer', nullable: true },
            price: { type: 'number' },
            duration: { type: 'string' },
            image_url: { type: 'string' },
            status: { type: 'string', enum: ['draft', 'published', 'closed'] },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        CourseCategory: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            slug: { type: 'string' },
            description: { type: 'string' },
            icon: { type: 'string', nullable: true },
            is_active: { type: 'boolean' },
          },
        },
        MemberTransaction: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            transaction_id: { type: 'string' },
            member_id: { type: 'integer' },
            member_name: { type: 'string' },
            type: { type: 'string' },
            amount: { type: 'number' },
            status: { type: 'string' },
            notes: { type: 'string' },
            payment_method: { type: 'string' },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        MemberActivity: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            member_id: { type: 'integer' },
            activity_type: { type: 'string' },
            description: { type: 'string' },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        Publication: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            code: { type: 'string' },
            isbn: { type: 'string' },
            title: { type: 'string' },
            author: { type: 'string' },
            slug: { type: 'string' },
            publisher_id: { type: 'integer' },
            collection_id: { type: 'integer' },
            description: { type: 'string' },
            cover_image: { type: 'string' },
            publication_year: { type: 'integer' },
            language: { type: 'string' },
            pages: { type: 'integer' },
            is_digital: { type: 'boolean' },
            status: { type: 'string' },
            media_type: { type: 'string' },
          },
        },
        Publisher: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            slug: { type: 'string' },
            description: { type: 'string' },
            address: { type: 'string' },
            phone: { type: 'string' },
            email: { type: 'string' },
            website: { type: 'string' },
            status: { type: 'string' },
          },
        },
        Author: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            slug: { type: 'string' },
            bio: { type: 'string' },
            nationality: { type: 'string' },
            status: { type: 'string' },
          },
        },
        News: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            title: { type: 'string' },
            slug: { type: 'string' },
            summary: { type: 'string' },
            content: { type: 'string' },
            status: { type: 'string', enum: ['draft', 'published', 'archived'] },
            image_url: { type: 'string' },
            author: { type: 'string' },
            read_time: { type: 'string' },
            published_date: { type: 'string', format: 'date' },
            is_featured: { type: 'boolean' },
          },
        },
        Member: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            card_number: { type: 'string' },
            full_name: { type: 'string' },
            email: { type: 'string' },
            phone: { type: 'string' },
            balance: { type: 'number' },
            status: { type: 'string' },
            membership_expires: { type: 'string', format: 'date-time' },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  apis: ['./src/routes/*.js'],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = { swaggerSpec };
