const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Thư viện TN CMS API',
      version: '2026.1.0',
      description: [
        '## API Documentation - Thư viện TN Backend',
        '',
        'Hệ thống RESTful API phục vụ **CMS Quản trị** và **Mobile App 2026**.',
        '',
        '### Xác thực',
        'Sử dụng **Bearer JWT Token** cho endpoint `/api/admin/*` và `/api/reader/*`.',
        'Lấy token tại `POST /api/auth/login`.',
        '',
        '### Cấu trúc Response chuẩn (7 trường)',
        '```json',
        '{',
        '  "code": 0,',
        '  "errorId": null,',
        '  "appId": null,',
        '  "success": true,',
        '  "message": "Thao tác thành công",',
        '  "data": { ... },',
        '  "errors": null',
        '}',
        '```',
        '',
        '### Cấu trúc Item ấn phẩm Mobile (7 trường)',
        '```json',
        '{',
        '  "id": 1,',
        '  "nhanDe": "Tên sách",',
        '  "tacGia": "Tác giả",',
        '  "anhDaiDien": "https://...",',
        '  "namXuatBan": 2023,',
        '  "nhaXuatBan": "NXB...",',
        '  "trang": 320',
        '}',
        '```',
      ].join('\n'),
    },
    servers: [{ url: 'http://localhost:5000', description: 'Local Development Server' }],
    tags: [
      { name: 'Auth', description: 'Xác thực và phân quyền người dùng' },
      { name: 'Admin Dashboard', description: 'API tổng quan hệ thống dành cho Quản trị viên' },
      { name: 'Admin Books', description: 'Quản lý ấn phẩm, sách, tác giả và nhà xuất bản' },
      { name: 'Admin News', description: 'Quản lý tin tức, bài viết và danh mục tin tức' },
      { name: 'Admin Loans', description: 'Quản lý mượn trả sách, gia hạn và đặt chỗ' },
      { name: 'Admin Members', description: 'Quản lý hội viên, nâng cấp gói và giao dịch nạp tiền' },
      { name: 'Admin Media', description: 'Quản lý thư viện hình ảnh và tệp tin' },
      { name: 'Admin System', description: 'Quản lý người dùng, vai trò, quyền và cài đặt hệ thống' },
      { name: 'Resource Hub', description: '🔵 [Mobile] Khám phá và điều hướng tài nguyên thư viện' },
      { name: 'Public Home', description: '🔵 [Mobile] Dữ liệu trang chủ: Banner, đề xuất, xu hướng' },
      { name: 'Public Books', description: '🔵 [Mobile] Xem chi tiết ấn phẩm' },
      { name: 'Public Search', description: '🔵 [Mobile] Tìm kiếm ấn phẩm công khai' },
      { name: 'Public News', description: '🔵 [Mobile] Tin tức dành cho người đọc' },
      { name: 'Public Membership', description: '🔵 [Mobile] Thông tin gói hội viên' },
      { name: 'App Reader', description: '🔵 [Mobile] API dành riêng cho tài khoản người đọc' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'JWT Token nhận được từ POST /api/auth/login',
        },
      },
      schemas: {
        // ── RESPONSE CƠ SỞ 7 TRƯỜNG ──────────────────────────────
        BaseResponse: {
          type: 'object',
          description: 'Response chuẩn 7 trường của toàn hệ thống',
          properties: {
            code:    { type: 'integer',  example: 0,    description: '0 = thành công, khác 0 = lỗi' },
            errorId: { type: 'string',   nullable: true, example: null, description: 'Mã lỗi (null nếu OK)' },
            appId:   { type: 'string',   nullable: true, example: null, description: 'App định danh' },
            success: { type: 'boolean',  example: true },
            message: { type: 'string',   example: 'Thao tác thành công' },
            data:    { description: 'Dữ liệu trả về' },
            errors:  { type: 'array',    nullable: true, example: null, description: 'Chi tiết lỗi' },
          },
        },
        ErrorResponse: {
          type: 'object',
          description: 'Response lỗi chuẩn 7 trường',
          properties: {
            code:    { type: 'integer', example: 500 },
            errorId: { type: 'string',  example: 'INTERNAL_SERVER_ERROR' },
            appId:   { type: 'string',  nullable: true, example: null },
            success: { type: 'boolean', example: false },
            message: { type: 'string',  example: 'Đã có lỗi hệ thống xảy ra' },
            data:    { nullable: true,  example: null },
            errors:  { type: 'array',  items: { type: 'string' }, example: ['ValidationError'] },
          },
        },

        // ── ITEM ẤN PHẨM MOBILE (7 TRƯỜNG) ──────────────────────
        MobileItem: {
          type: 'object',
          description: 'Item ấn phẩm chuẩn 7 trường dành cho Mobile App',
          properties: {
            id:         { type: 'integer', example: 1 },
            nhanDe:     { type: 'string',  example: 'Lập trình Node.js nâng cao', description: 'Nhãn đề / Tiêu đề' },
            tacGia:     { type: 'string',  example: 'Nguyễn Văn A',              description: 'Tác giả' },
            anhDaiDien: { type: 'string',  example: 'https://cdn.example.com/book.jpg', description: 'URL ảnh bìa' },
            namXuatBan: { type: 'integer', example: 2023,                        description: 'Năm xuất bản' },
            nhaXuatBan: { type: 'string',  example: 'NXB Khoa học Kỹ thuật',    description: 'Nhà xuất bản' },
            trang:      { type: 'integer', example: 320,                         description: 'Số trang' },
          },
        },

        // ── PHÂN TRANG CHUẨN ─────────────────────────────────────
        PaginatedResponse: {
          type: 'object',
          description: 'Wrapper phân trang cho danh sách Mobile App',
          properties: {
            items:        { type: 'array',   items: { $ref: '#/components/schemas/MobileItem' } },
            totalRecords: { type: 'integer', example: 100 },
            pageIndex:    { type: 'integer', example: 1 },
            pageSize:     { type: 'integer', example: 10 },
            totalPages:   { type: 'integer', example: 10 },
          },
        },
        Pagination: {
          type: 'object',
          properties: {
            page:       { type: 'integer', example: 1 },
            limit:      { type: 'integer', example: 20 },
            total:      { type: 'integer', example: 100 },
            totalPages: { type: 'integer', example: 5 },
          },
        },

        // ── RESOURCE HUB ─────────────────────────────────────────
        ResourceTreeNode: {
          type: 'object',
          description: 'Nút trong cây tài nguyên (Tree-view) của Resource Hub',
          properties: {
            label:    { type: 'string',  example: 'Tài liệu in',     description: 'Nhãn hiển thị' },
            value:    { type: 'string',  nullable: true, example: 'print-hub', description: 'Alias (dùng cho POST /alias)' },
            router:   { type: 'string',  nullable: true, example: 'search?type=basic' },
            icon:     { type: 'string',  example: 'fa fa-book' },
            children: { type: 'array',   nullable: true, items: { $ref: '#/components/schemas/ResourceTreeNode' } },
          },
        },
        ResourceTab: {
          type: 'object',
          description: 'Tab điều hướng trên Dashboard Resource Hub',
          properties: {
            id:    { type: 'string', example: 'trending' },
            label: { type: 'string', example: 'Xu hướng' },
            icon:  { type: 'string', example: 'trending-up' },
            type:  { type: 'string', enum: ['trending', 'favorite', 'views', 'rating'] },
          },
        },

        // ── SCHEMAS NGHIỆP VỤ ────────────────────────────────────
        AuditLog: {
          type: 'object',
          properties: {
            id:          { type: 'integer' },
            user_id:     { type: 'integer', nullable: true },
            user_name:   { type: 'string' },
            action:      { type: 'string', example: 'UPDATE' },
            module:      { type: 'string', example: 'MEMBER' },
            entity_id:   { type: 'string' },
            description: { type: 'string' },
            old_data:    { type: 'object', nullable: true },
            new_data:    { type: 'object', nullable: true },
            ip_address:  { type: 'string' },
            created_at:  { type: 'string', format: 'date-time' },
          },
        },
        MembershipRequest: {
          type: 'object',
          properties: {
            id:          { type: 'integer' },
            member_id:   { type: 'integer' },
            member_name: { type: 'string' },
            plan_id:     { type: 'integer' },
            plan_name:   { type: 'string' },
            amount:      { type: 'number' },
            status:      { type: 'string', enum: ['pending', 'approved', 'rejected'] },
            created_at:  { type: 'string', format: 'date-time' },
          },
        },
        BookLoan: {
          type: 'object',
          properties: {
            id:          { type: 'integer' },
            member_id:   { type: 'integer' },
            member_name: { type: 'string' },
            book_title:  { type: 'string' },
            borrow_date: { type: 'string', format: 'date-time' },
            due_date:    { type: 'string', format: 'date-time' },
            return_date: { type: 'string', format: 'date-time', nullable: true },
            status:      { type: 'string', enum: ['borrowing', 'returned', 'overdue', 'lost'] },
            fine_amount: { type: 'number', default: 0 },
          },
        },
        Publication: {
          type: 'object',
          properties: {
            id:               { type: 'integer' },
            code:             { type: 'string' },
            isbn:             { type: 'string' },
            title:            { type: 'string' },
            author:           { type: 'string' },
            slug:             { type: 'string' },
            publisher_name:   { type: 'string', nullable: true },
            description:      { type: 'string' },
            cover_image:      { type: 'string' },
            thumbnail:        { type: 'string' },
            publication_year: { type: 'integer' },
            pages:            { type: 'integer', nullable: true },
            status:           { type: 'string', default: 'available' },
            media_type:       { type: 'string', enum: ['Physical', 'Digital', 'Hybrid'] },
            is_digital:       { type: 'boolean' },
            rating_average:   { type: 'number' },
            total_reviews:    { type: 'integer' },
            dominant_color:   { type: 'string', example: '#4f46e5' },
            created_at:       { type: 'string', format: 'date-time' },
          },
        },
        Publisher: {
          type: 'object',
          properties: {
            id:          { type: 'integer' },
            name:        { type: 'string' },
            slug:        { type: 'string' },
            description: { type: 'string', nullable: true },
            status:      { type: 'string', default: 'active' },
          },
        },
        Author: {
          type: 'object',
          properties: {
            id:          { type: 'integer' },
            name:        { type: 'string' },
            slug:        { type: 'string' },
            bio:         { type: 'string', nullable: true },
            nationality: { type: 'string', nullable: true },
            status:      { type: 'string', default: 'active' },
          },
        },
        News: {
          type: 'object',
          properties: {
            id:             { type: 'integer' },
            title:          { type: 'string' },
            slug:           { type: 'string' },
            summary:        { type: 'string' },
            status:         { type: 'string', enum: ['draft', 'published', 'archived'] },
            image_url:      { type: 'string', nullable: true },
            is_featured:    { type: 'boolean', default: false },
            published_date: { type: 'string', format: 'date' },
          },
        },
        Member: {
          type: 'object',
          properties: {
            id:                   { type: 'integer' },
            card_number:          { type: 'string' },
            full_name:            { type: 'string' },
            email:                { type: 'string' },
            phone:                { type: 'string' },
            balance:              { type: 'number', default: 0 },
            status:               { type: 'string', default: 'active' },
            membership_expires:   { type: 'string', format: 'date-time', nullable: true },
            created_at:           { type: 'string', format: 'date-time' },
          },
        },
        MediaFile: {
          type: 'object',
          properties: {
            id:         { type: 'integer' },
            name:       { type: 'string' },
            file_path:  { type: 'string' },
            file_type:  { type: 'string' },
            file_size:  { type: 'integer' },
            created_at: { type: 'string', format: 'date-time' },
          },
        },
        Notification: {
          type: 'object',
          properties: {
            id:           { type: 'integer' },
            recipient_id: { type: 'integer' },
            title:        { type: 'string' },
            message:      { type: 'string' },
            type:         { type: 'string' },
            is_read:      { type: 'boolean', default: false },
            created_at:   { type: 'string', format: 'date-time' },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  apis: ['./src/routes/*.js', './src/routes/reader/*.js'],
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = { swaggerSpec };
